name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20.4"
      - name: Run Mage build linux amd64
        uses: magefile/mage-action@v2
        env:
          GOOS: linux
          GOARCH: amd64
        with:
          version: latest
          args: build
      - name: Run Mage build linux arm64
        uses: magefile/mage-action@v2
        env:
          GOOS: linux
          GOARCH: arm64
        with:
          version: latest
          args: build
      - name: Run Mage build darwin amd64
        uses: magefile/mage-action@v2
        env:
          GOOS: darwin
          GOARCH: amd64
        with:
          version: latest
          args: build
      - name: Run Mage build darwin arm64
        uses: magefile/mage-action@v2
        env:
          GOOS: darwin
          GOARCH: arm64
        with:
          version: latest
          args: build
      - name: Run Mage build windows amd64
        uses: magefile/mage-action@v2
        env:
          GOOS: windows
          GOARCH: amd64
        with:
          version: latest
          args: build
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          prerelease: contains(github.ref, 'rc')
          generate_release_notes: true
