name: validate

on: pull_request

jobs:
  lint:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20.4"
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: mage validate
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: validate
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20.4"
      - name: mage test
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test